export const temporalRecolectores = [
    {
      id: 1,
      name: "Juan Pérez",
      description: "Recolector de residuos reciclables con 5 años de experiencia.",
      photo: "https://example.com/photo1.jpg",
      rate: 4.5,
      credentialNumber: 1001,
    },
    {
      id: 2,
      name: "María López",
      description: "Experta en la recolección de plásticos y papel.",
      photo: "https://example.com/photo2.jpg",
      rate: 4.7,
      credentialNumber: 1002,
    },
    {
      id: 3,
      name: "Carlos García",
      description: "Recolector de residuos orgánicos y reciclables.",
      photo: "https://example.com/photo3.jpg",
      rate: 4.6,
      credentialNumber: 1003,
    },
    {
      id: 4,
      name: "Ana Torres",
      description: "Experta en la recolección de plásticos y papel.",
      photo: "https://example.com/photo4.jpg",
      rate: 4.8,
      credentialNumber: 1004,
    },
    {
      id: 5,
      name: "Luis Martínez",
      description: "Especialista en recolección de vidrio y metales.",
      photo: "https://example.com/photo5.jpg",
      rate: 4.4,
      credentialNumber: 1005,
    },
    {
      id: 6,
      name: "Sofía Ramírez",
      description: "Recolectora con enfoque en residuos tecnológicos.",
      photo: "https://example.com/photo6.jpg",
      rate: 4.9,
      credentialNumber: 1006,
    },
    {
      id: 7,
      name: "Pedro Fernández",
      description: "Experto en separación y clasificación de residuos.",
      photo: "https://example.com/photo7.jpg",
      rate: 4.3,
      credentialNumber: 1007,
    },
    {
      id: 8,
      name: "Lucía Morales",
      description: "Recolectora de residuos orgánicos en zonas rurales.",
      photo: "https://example.com/photo8.jpg",
      rate: 4.7,
      credentialNumber: 1008,
    },
    {
      id: 9,
      name: "Diego Rojas",
      description: "Especialista en residuos peligrosos y su tratamiento.",
      photo: "https://example.com/photo9.jpg",
      rate: 4.2,
      credentialNumber: 1009,
    },
    {
      id: 10,
      name: "Valeria Herrera",
      description: "Recolectora con experiencia en campañas ecológicas.",
      photo: "https://example.com/photo10.jpg",
      rate: 4.6,
      credentialNumber: 1010,
    },
    {
      id: 11,
      name: "Miguel Castro",
      description: "Recolector urbano con 3 años de experiencia.",
      photo: "https://example.com/photo11.jpg",
      rate: 4.5,
      credentialNumber: 1011,
    },
    {
      id: 12,
      name: "Camila Vargas",
      description: "Especialista en reciclaje de cartón y papel.",
      photo: "https://example.com/photo12.jpg",
      rate: 4.8,
      credentialNumber: 1012,
    },
    {
      id: 13,
      name: "Andrés Silva",
      description: "Recolector con experiencia en barrios marginales.",
      photo: "https://example.com/photo13.jpg",
      rate: 4.1,
      credentialNumber: 1013,
    },
    {
      id: 14,
      name: "Daniela Gómez",
      description: "Recolectora ecológica con enfoque educativo.",
      photo: "https://example.com/photo14.jpg",
      rate: 4.9,
      credentialNumber: 1014,
    },
    {
      id: 15,
      name: "José Molina",
      description: "Recolector de materiales reutilizables.",
      photo: "https://example.com/photo15.jpg",
      rate: 4.4,
      credentialNumber: 1015,
    },
    {
      id: 16,
      name: "Florencia Díaz",
      description: "Experta en campañas de concienciación ambiental.",
      photo: "https://example.com/photo16.jpg",
      rate: 4.6,
      credentialNumber: 1016,
    },
    {
      id: 17,
      name: "Héctor Salinas",
      description: "Recolector de zonas urbanas con alto tráfico.",
      photo: "https://example.com/photo17.jpg",
      rate: 4.3,
      credentialNumber: 1017,
    },
    {
      id: 18,
      name: "Julieta Peña",
      description: "Recolectora con enfoque en compostaje urbano.",
      photo: "https://example.com/photo18.jpg",
      rate: 4.7,
      credentialNumber: 1018,
    },
    {
      id: 19,
      name: "Ramiro Ortega",
      description: "Recolector de residuos industriales no peligrosos.",
      photo: "https://example.com/photo19.jpg",
      rate: 4.2,
      credentialNumber: 1019,
    },
    {
      id: 20,
      name: "Elena Rivas",
      description: "Experta en reciclaje domiciliario eficiente.",
      photo: "https://example.com/photo20.jpg",
      rate: 4.8,
      credentialNumber: 1020,
    },
    {
      id: 21,
      name: "Oscar Méndez",
      description: "Recolector con experiencia en eventos masivos.",
      photo: "https://example.com/photo21.jpg",
      rate: 4.5,
      credentialNumber: 1021,
    },
    {
      id: 22,
      name: "Rocío Aguirre",
      description: "Recolectora de residuos orgánicos y compostables.",
      photo: "https://example.com/photo22.jpg",
      rate: 4.9,
      credentialNumber: 1022,
    },
    {
      id: 23,
      name: "Gabriel Ibáñez",
      description: "Recolector en zonas rurales con acceso limitado.",
      photo: "https://example.com/photo23.jpg",
      rate: 4.1,
      credentialNumber: 1023,
    },
    {
      id: 24,
      name: "Mónica Cruz",
      description: "Recolectora con conocimiento en clasificación de residuos.",
      photo: "https://example.com/photo24.jpg",
      rate: 4.6,
      credentialNumber: 1024,
    },
    {
      id: 25,
      name: "Esteban Ruiz",
      description: "Recolector con experiencia en reciclaje de metales.",
      photo: "https://example.com/photo25.jpg",
      rate: 4.4,
      credentialNumber: 1025,
    },
    {
      id: 26,
      name: "Paula Figueroa",
      description: "Recolectora comunitaria con enfoque social.",
      photo: "https://example.com/photo26.jpg",
      rate: 4.7,
      credentialNumber: 1026,
    },
    {
      id: 27,
      name: "Bruno Navarro",
      description: "Recolector enfocado en educación ambiental.",
      photo: "https://example.com/photo27.jpg",
      rate: 4.6,
      credentialNumber: 1027,
    },
    {
      id: 28,
      name: "Natalia Paredes",
      description: "Recolectora voluntaria en campañas verdes.",
      photo: "https://example.com/photo28.jpg",
      rate: 4.8,
      credentialNumber: 1028,
    },
    {
      id: 29,
      name: "Álvaro Ponce",
      description: "Recolector eficiente con enfoque en sostenibilidad.",
      photo: "https://example.com/photo29.jpg",
      rate: 4.3,
      credentialNumber: 1029,
    },
    {
      id: 30,
      name: "Teresa Blanco",
      description: "Recolectora con más de 10 años de experiencia.",
      photo: "https://example.com/photo30.jpg",
      rate: 5.0,
      credentialNumber: 1030,
    },
  ];
  