export const temporalRecolectores = [
  {
    photo: "https://example.com/photo1.jpg",
    name: "Juan Pérez",
    ci: "12345678",
    zoneRecolector: "Zona Sur",
    credentialNumber: "RC-001",
    rate: 4.5,
  },
  {
    photo: "https://example.com/photo2.jpg",
    name: "María López",
    ci: "23456789",
    zoneRecolector: "Zona Norte",
    credentialNumber: "RC-002",
    rate: 4.7,
  },
  {
    photo: "https://example.com/photo3.jpg",
    name: "Carlos García",
    ci: "34567890",
    zoneRecolector: "Zona Este",
    credentialNumber: "RC-003",
    rate: 4.6,
  },
  {
    photo: "https://example.com/photo4.jpg",
    name: "Ana Torres",
    ci: "45678901",
    zoneRecolector: "Zona Oeste",
    credentialNumber: "RC-004",
    rate: 4.8,
  },
  {
    photo: "https://example.com/photo5.jpg",
    name: "Luis Martínez",
    ci: "56789012",
    zoneRecolector: "Zona Central",
    credentialNumber: "RC-005",
    rate: 4.4,
  },
  {
    photo: "https://example.com/photo6.jpg",
    name: "Sofía Ramírez",
    ci: "67890123",
    zoneRecolector: "Zona Sur",
    credentialNumber: "RC-006",
    rate: 4.9,
  },
  {
    photo: "https://example.com/photo7.jpg",
    name: "Pedro Fernández",
    ci: "78901234",
    zoneRecolector: "Zona Norte",
    credentialNumber: "RC-007",
    rate: 4.3,
  },
  {
    photo: "https://example.com/photo8.jpg",
    name: "Lucía Morales",
    ci: "89012345",
    zoneRecolector: "Zona Este",
    credentialNumber: "RC-008",
    rate: 4.7,
  },
  {
    photo: "https://example.com/photo9.jpg",
    name: "Diego Rojas",
    ci: "90123456",
    zoneRecolector: "Zona Oeste",
    credentialNumber: "RC-009",
    rate: 4.2,
  },
  {
    photo: "https://example.com/photo10.jpg",
    name: "Valeria Herrera",
    ci: "01234567",
    zoneRecolector: "Zona Central",
    credentialNumber: "RC-010",
    rate: 4.6,
  },
  {
    photo: "https://example.com/photo11.jpg",
    name: "Miguel Castro",
    ci: "11234567",
    zoneRecolector: "Zona Sur",
    credentialNumber: "RC-011",
    rate: 4.5,
  },
  {
    photo: "https://example.com/photo12.jpg",
    name: "Camila Vargas",
    ci: "12234567",
    zoneRecolector: "Zona Norte",
    credentialNumber: "RC-012",
    rate: 4.8,
  },
  {
    photo: "https://example.com/photo13.jpg",
    name: "Andrés Silva",
    ci: "13234567",
    zoneRecolector: "Zona Este",
    credentialNumber: "RC-013",
    rate: 4.1,
  },
  {
    photo: "https://example.com/photo14.jpg",
    name: "Daniela Gómez",
    ci: "14234567",
    zoneRecolector: "Zona Oeste",
    credentialNumber: "RC-014",
    rate: 4.9,
  },
  {
    photo: "https://example.com/photo15.jpg",
    name: "José Molina",
    ci: "15234567",
    zoneRecolector: "Zona Central",
    credentialNumber: "RC-015",
    rate: 4.4,
  },
  {
    photo: "https://example.com/photo16.jpg",
    name: "Florencia Díaz",
    ci: "16234567",
    zoneRecolector: "Zona Sur",
    credentialNumber: "RC-016",
    rate: 4.6,
  },
  {
    photo: "https://example.com/photo17.jpg",
    name: "Héctor Salinas",
    ci: "17234567",
    zoneRecolector: "Zona Norte",
    credentialNumber: "RC-017",
    rate: 4.3,
  },
  {
    photo: "https://example.com/photo18.jpg",
    name: "Julieta Peña",
    ci: "18234567",
    zoneRecolector: "Zona Este",
    credentialNumber: "RC-018",
    rate: 4.7,
  },
  {
    photo: "https://example.com/photo19.jpg",
    name: "Ramiro Ortega",
    ci: "19234567",
    zoneRecolector: "Zona Oeste",
    credentialNumber: "RC-019",
    rate: 4.2,
  },
  {
    photo: "https://example.com/photo20.jpg",
    name: "Elena Rivas",
    ci: "20234567",
    zoneRecolector: "Zona Central",
    credentialNumber: "RC-020",
    rate: 4.8,
  },
  {
    photo: "https://example.com/photo21.jpg",
    name: "Oscar Méndez",
    ci: "21234567",
    zoneRecolector: "Zona Sur",
    credentialNumber: "RC-021",
    rate: 4.5,
  },
  {
    photo: "https://example.com/photo22.jpg",
    name: "Rocío Aguirre",
    ci: "22234567",
    zoneRecolector: "Zona Norte",
    credentialNumber: "RC-022",
    rate: 4.9,
  },
  {
    photo: "https://example.com/photo23.jpg",
    name: "Gabriel Ibáñez",
    ci: "23234567",
    zoneRecolector: "Zona Este",
    credentialNumber: "RC-023",
    rate: 4.1,
  },
  {
    photo: "https://example.com/photo24.jpg",
    name: "Mónica Cruz",
    ci: "24234567",
    zoneRecolector: "Zona Oeste",
    credentialNumber: "RC-024",
    rate: 4.6,
  },
  {
    photo: "https://example.com/photo25.jpg",
    name: "Esteban Ruiz",
    ci: "25234567",
    zoneRecolector: "Zona Central",
    credentialNumber: "RC-025",
    rate: 4.4,
  },
  {
    photo: "https://example.com/photo26.jpg",
    name: "Paula Figueroa",
    ci: "26234567",
    zoneRecolector: "Zona Sur",
    credentialNumber: "RC-026",
    rate: 4.7,
  },
  {
    photo: "https://example.com/photo27.jpg",
    name: "Bruno Navarro",
    ci: "27234567",
    zoneRecolector: "Zona Norte",
    credentialNumber: "RC-027",
    rate: 4.6,
  },
  {
    photo: "https://example.com/photo28.jpg",
    name: "Natalia Paredes",
    ci: "28234567",
    zoneRecolector: "Zona Este",
    credentialNumber: "RC-028",
    rate: 4.8,
  },
  {
    photo: "https://example.com/photo29.jpg",
    name: "Álvaro Ponce",
    ci: "29234567",
    zoneRecolector: "Zona Oeste",
    credentialNumber: "RC-029",
    rate: 4.3,
  },
  {
    photo: "https://example.com/photo30.jpg",
    name: "Teresa Blanco",
    ci: "30234567",
    zoneRecolector: "Zona Central",
    credentialNumber: "RC-030",
    rate: 5.0,
  },
];
